[package]
name = "rust"
version = "0.1.0"
authors = ["Agnieszka <agnieszka.pietruczuk@docplanner.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
findshlibs = "0.8.0"
